[package]
name = "mailcrab-backend"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
mailin = "0.6"
mailin-embedded = { version = "0.7", features = ["rtls"] }
axum = { version = "0.5", features = ["ws", "headers"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["io-util", "sync"] }
tower-http = { version = "0.3.0", features = ["fs", "trace"] }
futures = "0.3"
async-stream = "0.3"
base64 = "0.13"
mail-parser = "0.6"
serde_json = "1.0"
uuid = { version = "1.2", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
humansize = "2.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
chrono = "0.4"
chrono-humanize = "0.2"

[dev-dependencies]
lettre = "0.9"
lettre_email = "0.9"
fake = { version = "2.5", features=['derive']}
rand = "0.8"